##Python numpy Arrays

Numpy

Numpy is a general-purpose array_processing package.it provides a high performance multidimensional array object,and tools for working with these arrays .it is the fundamental package for for scientific computing with python.


What is an Array
an array is a data structure that stores values of same datatype.in python,This is the main difference between arrays and lists.While python lists can contain values corresponding to different data types ,arrays in python can only contain values corresponding to same data type.


In [63]:
##import library
import numpy as np #np is aliase

In [64]:
list=[1,2,3,4]

In [65]:
arr=np.array(list) #list is convert to array


The output of the above line is array([1, 2, 3, 4]) which is a single dimension array because it has one pair of square bracket.If there will there will more than one pair of square brackets than it will be Multidimensional array.


In [66]:
print(arr)

[1 2 3 4]


In [67]:
type(arr)

numpy.ndarray

In [68]:
list1=[1,2,3,4]
list2=[2,3,4,5]
list3=[3,4,5,6]


In [72]:
arr1=np.array([list1,list2,list3])

In [74]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [75]:
arr1.shape

(3, 4)

In [76]:
arr.shape

(4,)

In [77]:
arr

array([1, 2, 3, 4])

In [78]:
#indexing :    always starts with 0
arr[3]

4

In [79]:
arr[-1]

4

In [80]:
arr[0]

1

In [81]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [82]:
arr1[0,0]

1

In [83]:
arr1[2,3]

6

In [84]:
arr1[:1]

array([[1, 2, 3, 4]])

In [85]:
arr1[:2]

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [86]:
arr[1]=10

In [87]:
arr

array([ 1, 10,  3,  4])

In [88]:
arr[1:]

array([10,  3,  4])

In [89]:
arr[1:3]


array([10,  3])

In [91]:
arr[:-1]
#remove last element means one element minus from the all elements

array([ 1, 10,  3])

In [92]:
arr[::-1]
#double colon will reverse the element of the array

array([ 4,  3, 10,  1])

In [93]:
arr[::-2]
#from last elements jumps two steps and print

array([ 4, 10])

In [94]:
arr[::]
#prints all the elements

array([ 1, 10,  3,  4])

In [95]:
arr1


array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [98]:
#indexing two dimensional array
arr1[:,1]

array([2, 3, 4])

In [103]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [105]:
arr1[1:,2:]

array([[4, 5],
       [5, 6]])

In [106]:
arr1[0:,2:]

array([[3, 4],
       [4, 5],
       [5, 6]])

In [107]:
arr1[0:,2:].shape

(3, 2)

In [108]:
arr1[:,0:3]

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [109]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [125]:
arr1[:,0::3]
#to retreive first and last column

array([[1, 4],
       [2, 5],
       [3, 6]])

In [126]:
arr1[:,0::2]

array([[1, 3],
       [2, 4],
       [3, 5]])

In [127]:
##EDA
arr

array([ 1, 10,  3,  4])

In [128]:
arr<2

array([ True, False, False, False])

In [129]:
arr[arr<2]
#specific element with index

array([1])

In [130]:
#reshape
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [131]:
arr1.reshape(6,2)

array([[1, 2],
       [3, 4],
       [2, 3],
       [4, 5],
       [3, 4],
       [5, 6]])

In [132]:
arr1.reshape(12,1)


array([[1],
       [2],
       [3],
       [4],
       [2],
       [3],
       [4],
       [5],
       [3],
       [4],
       [5],
       [6]])

In [133]:
arr1.reshape(4,3)

array([[1, 2, 3],
       [4, 2, 3],
       [4, 5, 3],
       [4, 5, 6]])

In [137]:
##mechanism to create an array
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [139]:
np.arange(1,10,1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
np.arange(1,10,1).reshape(1,9,1)

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]])

In [145]:
np.arange(1,11,1).reshape(2,5,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [146]:
##operations 
arr

array([ 1, 10,  3,  4])

In [147]:
arr*arr

array([  1, 100,   9,  16])

In [148]:
arr + arr

array([ 2, 20,  6,  8])

In [149]:
arr1*arr

array([[ 1, 20,  9, 16],
       [ 2, 30, 12, 20],
       [ 3, 40, 15, 24]])

In [153]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [154]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [156]:
#random function
np.random.randint(10,50)

11

In [157]:
np.random.randint(10,50,4)

array([26, 40, 36, 37])

In [158]:
np.random.randint(10,50,4).reshape(2,2)

array([[39, 44],
       [48, 29]])

In [159]:
#randomly intialiaze based on normal distribution
np.random.randn(5,6)

array([[-0.28664174,  0.20275862,  0.75187141,  2.41184465, -0.33905533,
         0.31974334],
       [ 1.20208301, -0.46659204, -0.31621076,  2.04807744, -0.2083526 ,
         0.42799736],
       [-1.54630078, -0.31089993, -1.28807825,  0.02925922,  0.13053997,
         0.46689136],
       [ 0.82418991,  0.33850138,  0.55827609, -1.26747049, -0.09988568,
        -0.18257487],
       [-0.53199804, -0.12953897, -0.36222624, -0.38437097,  0.73710729,
        -0.62987423]])

In [161]:
#random_sample 
#returns values from 0.0 to 1.0
np.random.random_sample((4,7))


array([[0.28849549, 0.60064059, 0.38674428, 0.19492618, 0.8071447 ,
        0.17879448, 0.65015588],
       [0.42716272, 0.77192564, 0.30188274, 0.1630019 , 0.61311381,
        0.91653273, 0.59433479],
       [0.02266276, 0.79838903, 0.67933112, 0.72565467, 0.9007468 ,
        0.97650336, 0.98289372],
       [0.87939941, 0.77700416, 0.5307927 , 0.57791129, 0.47921357,
        0.16691807, 0.07602028]])